server:
  port: 3000

db:
  type: 'postgres'
  host: 'localhost'
  port: 5432
  username: 'postgres'
  password: 'Hossein1379'
  database: 'dynamic_portfolio'
  synchronize: true

jwt:
  expiresIn: 2.592e+6
  secret: 'Ho$$einSadeghi2000'


email:
  user: 'hskhabbaz@gmail.com'
  pass: 'Hossein1379'

telegram:
  token: '5316491780:AAGoNANFs5ktX3-f4FH9JZpFpnHrwKtYVzs'
